version: "2"
services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ${DATADIR}/docker/influxdb:/var/lib/influxdb
      # Mount for influxdb configuration
      #- ${DATADIR}/docker/influxdb/etc/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_DB=homeassistant
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - TZ=${TZ}
    networks:
      - docker-net
  
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: 1000:1000
    ports:
      - "3000:3000"
    restart: always
    networks:
      - docker-net
    volumes:
      - ${DATADIR}/docker/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.monitor.com
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    links:
      - influxdb
    depends_on:
      - influxdb
  
  
  
  telegraf:
    image: telegraf:1.20.3
    container_name: telegraf
    privileged: true
    #volumes:
       #- ${DATADIR}/docker/telegraf/:/etc/telegraf
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    ports:
      - '8125:8125/udp'
    networks:
      - docker-net
      
      
networks:
  docker-net:
    external:
      name: docker-net 
